# config file of code generator
global:
  author: melon
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: test
tasks:
  # 生成java实体
  - name: JavaEntity                                    # task name
    template: java_entity.tpl                           # template file from .cg/templates folder
    source-type: mysql                                  # table to entity
    table: user                                         # table name
    output: User.java                                   # output file name
    variables:                                          # variables for template
      package: com.example.dao.domain
    enable: true
  # 生成java mapper类
  - name: JavaMapper
    template: java_mapper.tpl
    source-type: mysql
    table: user
    output: UserMapper.java
    variables:
      package: com.example.dao.mapper
    enable: true
  # 生成java mybatis 的xml文件
  - name: JavaMapperXml
    template: java_mapper_xml.tpl
    source-type: mysql
    table: user
    output: UserMapper.xml
    enable: true