mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: test
  table: user

author: melon
base-package: com.example
module: cg

tasks:
  # 生成java实体类
  - name: JavaEntity
    template: java_entity.tpl
    output: .cg/output
    file-postfix: .java
    variables:
      sub-package: dao.domain
    enable: true
  # 生成java mapper接口
  - name: JavaMapper
    template: java_mapper.tpl
    output: .cg/output
    file-postfix: Mapper.java
    variables:
      sub-package: dao.mapper
      class-postfix: Mapper
    enable: true
  # 生成java mybatis 的xml文件
  - name: JavaMapperXml
    template: java_mapper_xml.tpl
    output: .cg/output
    file-postfix: Mapper.xml
    enable: true
  # 生成java service接口
  - name: JavaService
    template: java_service.tpl
    output: .cg/output
    file-postfix: Service.java
    variables:
      sub-package: service
      class-postfix: Service
    enable: true
  # 生成java services实现类
  - name: JavaServiceImpl
    template: java_service_impl.tpl
    output: .cg/output
    file-postfix: ServiceImpl.java
    variables:
      sub-package: service.impl
      class-postfix: ServiceImpl
    enable: true
  # 生成java controller类
  - name: JavaController
    template: java_controller.tpl
    output: .cg/output
    file-postfix: Controller.java
    variables:
      sub-package: controller
      class-postfix: Controller
    enable: true