mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: test
  table: user

author: melon
base-package: com.example
module: cg

tasks:
  # 生成java实体类
  - name: entity
    template: java_entity.tpl
    prefix: ""
    postfix: ""
    file-type: .java
    properties:
      sub-package: dao.entity
    enable: true
  # 生成java mapper接口
  - name: mapper
    template: java_mapper.tpl
    prefix: ""
    postfix: Mapper
    file-type: .java
    properties:
      sub-package: dao.mapper
    enable: true
  # 生成java mybatis 的xml文件
  - name: xml
    template: java_mapper_xml.tpl
    prefix: ""
    postfix: Mapper
    file-type: .xml
    enable: true
  # 生成java service接口
  - name: service
    template: java_service.tpl
    prefix: ""
    postfix: Service
    file-type: .java
    properties:
      sub-package: service
    enable: true
  # 生成java services实现类
  - name: serviceImpl
    template: java_service_impl.tpl
    prefix: ""
    postfix: ServiceImpl
    file-type: .java
    properties:
      sub-package: service.impl
    enable: true
  # 生成java controller类
  - name: controller
    template: java_controller.tpl
    prefix: ""
    postfix: Controller
    file-type: .java
    properties:
      sub-package: controller
    enable: true