# config file of code generator
mysql:
  username: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: test
tasks:
  - name: entity                                        # task name
    template: entity.tpl                                # template file from .cg/templates folder
    source-type: mysql                                  # table to entity
    table: user                                         # table name
    output: User.java                                   # output file name
    variables:                                          # variables for template
      package: com.example.dao.domain
    enable: true                                        # enable or disable the task
  - name: mapper
    template: mapper.tpl
    source-type: mysql
    table: user
    output: UserMapper.java
    variables:
      package: com.example.dao.mapper
    enable: true
  - name: mapper_xml
    template: mapper.xml.tpl
    source-type: mysql
    table: user
    output: UserMapper.xml
    enable: true
